### ISSUE TITLE
Battle system refact about Boss

### ISSUE THREAD

**Issue by hwanginseop** [Apptive-Game-Team/GyeMong#60]
### 전투 시스템 고도화
 - -[x] 공격 충돌 처리 **(피격판정)**
   - -[ ] 피격 효과 **(연출)**
   - -[x] 피격 이벤트
   - -[x] 보스 근접 공격 달기 **(콜라이더)**
 - -[ ] 방어시스템
   - 방어를 **잘**하면 패링이 됨
   - 방어는 기본적으로 데미지 감소 회피랑 차이를 둬야되니까

### 패턴 feat
 - -[x] 실드 **(수호자)**
   - -[x] 실드량 체크
### 패턴 refact
 - -[x] 백스텝/ 돌진 시 장애물 마주치면 멈추게 **(중간보스)** -> 걍 장애물 피하는 ai를 넣어야됨 ->박아놓고 근접공격만 추가
 - -[x] 백스텝 사거리 안에 있어도 완전 근접 아니면 안하게 조건 변경 **(중간보스)**
 - -[x] 큐브 낙하 도중 맞으면 같이 내려오는거 고치기 **(수호자)**
 - -[x] 럴커 범위 늘리기 **(수호자)**
 - -[x] 패턴 별 선딜 입력
 - -[x] 수호자 근접 공격 추가 **(수호자)**

**Comment by hwanginseop** [comment]
추적을 기본 행동으로 두고 패턴 발동시 속도를 0으로 고칠까....

**Comment by Monolong** [comment]
상태 써서 구현하는 게 낫지 않을까?

**Comment by hwanginseop** [comment]
굿 아이디어인데 그럼 맵 패턴이랑 보스 패턴을 분리할 필요가 있을 듯
ex) 럴커 = 보스패턴 / 가시바닥 = 맵 패턴
