### ISSUE TITLE
Enhancement Puzzle 1,3

### ISSUE THREAD

**Issue by Gimlocal** [Apptive-Game-Team/GyeMong#63]
- [x] 퍼즐1 고도화
    - [x] 미로안에서 플레이어 주변 어둡게 만들기
        - [x] 미로에 들어갈때 Fade Out같은 느낌으로 어두워지게 하기
    - [x] 미로 가운데 광장 같은거 만들기
    - [x] 미로 중간중간에 함정 만들기
    - [x] 나무 Prefab이 그림자에 안 가리는 오류 수정
- [x] 퍼즐3 고도화
    - [x] 제한시간 설정
    - [x] 그림을 좀더 어렵게 만들기 (몬드리안 스타일)
더 생각나면 추가 예정

**Comment by Monolong** [comment]
그림이 헷갈리는 그림이면 난이도가 올라갈까?

**Comment by hwanginseop** [comment]
오 의견 좋은데요

**Comment by Gimlocal** [comment]
그림이 헷갈리는게 어떤 느낌이죠?
니가 그린 기린 그림 같은건가

**Comment by Monolong** [comment]
약간 몬드리안의 그림 같은 느낌?
비슷한 패턴같은게 있는느낌
지금은 룬 그림인데 룬 그림으로 하면 너무 쉬우니까 동그라미때문에
